name: Build and Publish Embeddings

on:
  workflow_dispatch:

jobs:
  build-and-publish-embeddings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and push embeddings
        uses: cern-sis/gh-workflows/.github/actions/docker-build@v6.4.1
        with:
          context: ./ai-backend
          dockerfile: ./ai-backend/Dockerfile.embeddings
          platforms: linux/amd64
          cache: false
          registry: registry.cern.ch
          image: cern-sis/inspire/ai-embeddings
          tags: |
            latest
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
